[project]
name = "calculus"
version = "0.2.0"
description = "Advanced calculus library made by LegedsDaD"
readme = "README.md"
requires-python = ">=3.7"
license = {text = "MIT"}
authors = [
    {name = "LegedsDaD"}
]
